### PR TITLE
Feature: added payin card web support

### PR DESCRIPTION
**Pull request by godspeedelbow**
so we can iDeal payments with mangopay

### CODE REVIEW

**Comment by godspeedelbow** [comment]
@larafale any news on this?

**Comment by larafale** [comment]
hello @godspeedelbow to be honest i have no time at all to work on this for now, i can add you as a contributor on this repo if you want ?

**Comment by godspeedelbow** [comment]
yeah, totally, I'd love to help out. Maybe we can setup a quick skype call somewhere next week where you talk me through the design philosophy/technical architecture you've set up, so that I continue on the right track. Cheers, Eelke

**Comment by godspeedelbow** [comment]
Hi, @larafale how do you want to proceed with this?

**Comment by larafale** [comment]
let's skype, my username is "skypelarafale"

**Pull request merged**
